### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [anytrack/Google-Tag-Manager-Templates#1]
https://github.com/anytrack/Google-Tag-Manager-Templates/blob/82fc8f864612ad49c231ac145e77dea8c4633e9d/template.tpl#L72

 When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by shftlvch** [comment]
@semisight 👋, fixed in the newest version. Thank you.

**Comment by ljmalka** [comment]
> https://github.com/anytrack/Google-Tag-Manager-Templates/blob/82fc8f864612ad49c231ac145e77dea8c4633e9d/template.tpl#L72
> 
> When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

Hi @semisight - Issue fixed. 
Thank you for pointing out.
When will the template be public?
